# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e64839826afbbbce7c08e12bac6b4490630d5fe13222d64d8166de5ed393556538febb6c5883a5f71d5f294e8a9615711e81625e01dd2f609ba7cb1adc8f0b9

test:
  secret_key_base: 9827b110bd1cc7ed1db40008f5388be129ffa1881416022acf7a1742c16fc8a39ce7f31618149d077309fac2527f8b0409835a2a322300a42b9ba64dbc34bf78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
